### PR TITLE
sql/migrate: improve details on not clean error

### PR DESCRIPTION
**Pull request by masseelch**

### CODE REVIEW

**Review by a8m — APPROVED** [review]

**Comment by iwata** [comment]
This pull request breaks [ent@master](https://github.com/ent/ent/blob/master/dialect/sql/schema/atlas.go#L186).
When can you fix it?

**Comment by masseelch** [comment]
Hey @iwata, how does this PR break Ent?

**Comment by iwata** [comment]
The following error occurs.
`/pkg/mod/entgo.io/ent@v0.10.2-0.20220708182646-0f33b0bcb8ec/dialect/sql/schema/atlas.go:186:19: undefined: migrate.ErrNotClean`

>  It will, if we pull in the current master of Atlas into Ent, but we haven't done this yet.

Okay, can you fix it soon?
I'll use [this option](https://github.com/ariga/atlas/pull/931) with Ent.

**Comment by masseelch** [comment]
This shouldn't happen. Did you by any chance run `go get ariga.io/atlas@master` in your Ent repo (overriding the version in the module file)? 

Anyway, PR to "fix" this is up: https://github.com/ent/ent/pull/2739

Once that is merged, it will work again.

**Comment by iwata** [comment]
Thanks for your prompt action!
I'll wait to merge your PR.

**Pull request merged**
