### PR TITLE
Default value of string like field can be empty string `""` or `"null"`

### PR DESCRIPTION
**Pull request by fishead**
fix issue #625

### CODE REVIEW

**Comment by a8m** [comment]
Looks good! Thanks for the contribution @fishead ❤️ 🙏

**Comment by a8m** [comment]
I'll check why the CI is failing and will update you.

**Comment by a8m** [comment]
MariaDB renders the NULL default values as `NULL` string, I'll dig into this and will update. See `COLUMN_DEFAULT` and `COLUMN_DEFAULT IS NULL`:

```
SELECT `TABLE_NAME`, `COLUMN_NAME`, `COLUMN_TYPE`, `COLUMN_COMMENT`, `IS_NULLABLE`, `COLUMN_KEY`, `COLUMN_DEFAULT` IS NULL, `COLUMN_DEFAULT`, `EXTRA`, `CHARACTER_SET_NAME`, `COLLATION_NAME` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'test' AND `TABLE_NAME` IN ('pets') ORDER BY `ORDINAL_POSITION`;
+------------+-------------+-------------+----------------+-------------+------------+--------------------------+----------------+-------+--------------------+----------------+
| TABLE_NAME | COLUMN_NAME | COLUMN_TYPE | COLUMN_COMMENT | IS_NULLABLE | COLUMN_KEY | `COLUMN_DEFAULT` IS NULL | COLUMN_DEFAULT | EXTRA | CHARACTER_SET_NAME | COLLATION_NAME |
+------------+-------------+-------------+----------------+-------------+------------+--------------------------+----------------+-------+--------------------+----------------+
| pets       | id          | bigint(20)  |                | NO          | PRI        |                        1 | NULL           |       | NULL               | NULL           |
| pets       | owner_id    | bigint(20)  |                | YES         | MUL        |                        0 | NULL           |       | NULL               | NULL           |
+------------+-------------+-------------+----------------+-------------+------------+--------------------------+----------------+-------+--------------------+----------------+
```

**Comment by a8m** [comment]
OK, just checked that on https://mariadb.com/kb/en/information-schema-columns-table/ and this patch should solve the issue. Please, add it to the `mysql/inspect.go` file:

```diff
 // marDefaultExpr returns the correct schema.Expr based on the column attributes for MariaDB.
 func (i *inspect) marDefaultExpr(c *schema.Column, x string) schema.Expr {
+       // Unlike MySQL, NULL means default to NULL or no default.
+       if x == "NULL" {
+               return nil
+       }
        // From MariaDB 10.2.7, string-based literals are quoted to distinguish them from expressions.
        if i.gteV("10.2.7") && sqlx.IsQuoted(x, '\'') {
```

**Comment by a8m** [comment]
@fishead, you're also welcome to our atlas community on Discord 😃 
https://discord.com/invite/QhsmBAWzrC

**Comment by fishead** [comment]
@a8m PR updated. Thanks for the detail.

**Review by a8m — APPROVED** [review]

**Comment by a8m** [comment]
💯

**Pull request merged**
