### PR TITLE
doc/md: add homebrew installation instructions to docs

### PR DESCRIPTION
**Pull request by rotemtam**

### CODE REVIEW

**Review by yonidavidson — APPROVED** [review]
We still need to add the URL for whoever doesn't use brew.

**Comment by reneleonhardt** [comment]
Someone published a [bottle](https://github.com/Homebrew/homebrew-core/blob/main/Formula/a/atlas.rb) to homebrew-core, no tap needed anymore.

```shell
brew install atlas
```

**Comment by rotemtam** [comment]
This will get you the community build of Atlas which lacks many valuable features. See [community vs official build doc](https://atlasgo.io/community-edition).

**Comment by reneleonhardt** [comment]
Thanks for clarifying, maybe you could contribute a explaining description to the bottle (which just shows "Database toolkit") and your README.

**Pull request merged**
