### PR TITLE
sql/mysql: fix inspect.go check repeat bug

### PR DESCRIPTION
**Pull request by Weilence**
If two tables have fields with identical names and JSON data type, the migration generation process may encounter redundant checks.

```sql
CREATE TABLE `table_a` (
	`id` INT NOT NULL,
	`name` JSON NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `table_b` (
	`id` INT NOT NULL,
	`name` JSON NOT NULL,
	PRIMARY KEY (`id`)
);
```
will
```
+------------+-----------------+--------------------+----------+
| TABLE_NAME | CONSTRAINT_NAME | CHECK_CLAUSE       | ENFORCED |
+------------+-----------------+--------------------+----------+
| table_a    | name            | json_valid(`name`) | YES      |
| table_a    | name            | json_valid(`name`) | YES      |
+------------+-----------------+--------------------+----------+
```

### CODE REVIEW

**Comment by Weilence** [comment]
> > ```
> >     	Error Trace:	/home/runner/work/atlas/atlas/internal/integration/mysql_test.go:1490
> >    	            				/home/runner/work/atlas/atlas/internal/integration/integration_test.go:590
> >    	            				/home/runner/work/atlas/atlas/internal/integration/integration_test.go:99
> >    	            				/home/runner/work/atlas/atlas/internal/integration/mysql_test.go:84
> >    	            				/home/runner/work/atlas/atlas/internal/integration/mysql_test.go:64
> >    	Error:      	Received unexpected error:
> >    	            	mysql: querying "test" check constraints: Error 1054 (42S22): Unknown column 't2.TABLE_NAME' in 'on clause'
> > ```
> 
> CI is red. I'll try to debug it later today



> > ```
> >     	Error Trace:	/home/runner/work/atlas/atlas/internal/integration/mysql_test.go:1490
> >    	            				/home/runner/work/atlas/atlas/internal/integration/integration_test.go:590
> >    	            				/home/runner/work/atlas/atlas/internal/integration/integration_test.go:99
> >    	            				/home/runner/work/atlas/atlas/internal/integration/mysql_test.go:84
> >    	            				/home/runner/work/atlas/atlas/internal/integration/mysql_test.go:64
> >    	Error:      	Received unexpected error:
> >    	            	mysql: querying "test" check constraints: Error 1054 (42S22): Unknown column 't2.TABLE_NAME' in 'on clause'
> > ```
> 
> CI is red. I'll try to debug it later today

I am using MariaDB version 10.6.12. However, it appears that the `CHECK_CONSTRAINTS` table in MySQL does not have a `TABLE_NAME` field.

**Comment by Weilence** [comment]
I found that the MySQL documentation at https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html mentions that `CONSTRAINT_NAME` cannot be duplicated within each schema but MariaDB does not mention this.
image

Additionally, when creating a JSON column, MariaDB automatically adds a constraint, while MySQL does not. Therefore, there will be no issue with `table_a` and `table_b` in MySQL since they are not constrained.

**Comment by Weilence** [comment]
Hi @a8m, My PR has been pending for a while. Whenever you have time, could you please take a look? Your feedback would be greatly appreciated.

**Comment by a8m** [comment]
Hey @Weilence 👋 

I wanted to add a small (integration) test case for it. I'll pull the changes later today/tomorrow and handle this. Thanks 🙏

**Comment by a8m** [comment]
Hey! Just to update that I opened a PR to fix this issue: https://github.com/ariga/atlas/pull/2276

Give it a look, please. Unfortunately, your change didn't resolve the problem and I needed to create a different query for MariaDB.

**Pull request closed without merging**
