### PR TITLE
doc/website: add blog page

### PR DESCRIPTION
**Pull request by hedwigz**
* added blog page
* brought relevant posts from ariga.io
* fixed SQL syntax highlight

### CODE REVIEW

**Comment by rotemtam** [comment]
Screen Shot 2022-05-03 at 0 43 01

**Review by rotemtam — COMMENTED** [review]
Thanks for working on this!
See a screenshot I shared about how the top nav looks on mobile. 
Also, I think we can add a link to the blog in the footer as well. 

Also If you're adding top-nav to the rest of this site:
Screen Shot 2022-05-03 at 0 48 46
Perhaps its content should be consistent with the home page

**Comment by hedwigz** [comment]
> Thanks for working on this! See a screenshot I shared about how the top nav looks on mobile. Also, I think we can add a link to the blog in the footer as well.
> 
> Also If you're adding top-nav to the rest of this site: Screen Shot 2022-05-03 at 0 48 46 Perhaps its content should be consistent with the home page

* compacted links and removed CLI
* added docs link in the footer

image

**Review by rotemtam — APPROVED** [review]

**Pull request merged**
