### PR TITLE
sql/spanner: Use new spanner emulator and touch up tests

### PR DESCRIPTION
**Pull request by tmc**
As of 1.4.8 the Spanner emulator has DEFAULT support and this is a small change to include more use of defaults.

### CODE REVIEW

**Comment by tmc** [comment]
I believe that #1311 needs to go in for `generate-cmp` to pass.

**Review by a8m — APPROVED** [review]

**Comment by a8m** [comment]
Can I merge it, or do you want to fix it before?

**Comment by tmc** [comment]
> Can I merge it, or do you want to fix it before?

Since the previous step can (and does) update go.work.sum this step fails: `git checkout -` without a `-f` -- since that check is explicitly using master as long as master and this (or any other) branch cause different content in go.work.sum that step will fail.

**Comment by tmc** [comment]
(no-op push to re-trigger CI)

**Pull request merged**
